load("@rules_flex//flex/internal:toolchain.bzl", "flex_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

flex_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
