filegroup(
    name = "flex_repository_ext_bzl",
    srcs = ["flex_repository_ext.bzl"],
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "flex_toolchains_ext_bzl",
    srcs = ["flex_toolchains_ext.bzl"],
    visibility = ["//:__subpackages__"],
)
